# Generated by Django 4.2.1 on 2023-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
