# Generated by Django 4.2.1 on 2023-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_description_alter_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='avaliableForSale',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
