# Generated by Django 4.2.1 on 2023-07-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_salesoperations_house_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoperations',
            name='marketerCommission',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
