# Generated by Django 4.2.1 on 2023-07-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0003_marketer_createddate'),
        ('house', '0005_alter_salesoperations_marketercommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoperations',
            name='houseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='house.house'),
        ),
        migrations.AlterField(
            model_name='salesoperations',
            name='marketerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='marketer.marketer'),
        ),
    ]
