# Generated by Django 4.2.1 on 2023-07-01 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0002_alter_house_description_alter_house_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('min_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reference_code', models.CharField(max_length=20)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.house')),
            ],
        ),
    ]
