# Generated by Django 4.2.1 on 2023-07-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_description_alter_house_name'),
        ('marketer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketers', to='house.house'),
        ),
    ]
