# Generated by Django 4.2.1 on 2023-07-07 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0002_alter_marketer_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='createdDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
